### ISSUE TITLE
Issue with Cycling Cameras

### ISSUE THREAD

**Issue by ross8alex** [AndreiMisiukevich/Xamarin.Forms.Vonage#1]
When cycling the cameras (CrossVonage.Current.CycleCamera()) and exiting the page, then returning to the page, the camera no longer functions. If you cycle the camera only once, it partially functions, but with a greatly reduced framerate and with a general lagginess to the app, and if you cycle it any more eventually the app will crash altogether. with the error code:

CAMERA_DISCONNECTED (2): checkPidStatus:2443: The camera device has been disconnected'

I've been using the old version of your project for a few months now and was taking a look at this again since I ran into this issue; it seems to happen on both the old CrossOpenTok and new CrossVonage versions. From my own research it seems like this might be something having to do with DreamTeam's OpenTok.Android library, but I'm not sure since I couldn't find any other related issues.

**Comment by AndreiMisiukevich** [comment]
Hi @ross8alex and thanks for your report.
Unfortunately, I should say that I can't do much cuz it actually looks like the issue is not here (this plugin just calls CycleCamera of PublisherKit which is inside DreamTeam's lib... or even in native code)

I propose to move this issue to DreamTeam's repository (especially if the issue is reproducible w/out my lib

**Comment by ross8alex** [comment]
Ok I'll see if I can replicate the issue using DreamTeam's lib, thanks for your help.
